### ISSUE TITLE
Re-register with the agent when not available

### ISSUE THREAD

**Issue by Devatoria** [Devatoria/go-mesos-executor#27]
Allow executor to re-register with the agent, keeping containers running while agent is stopped

**Comment by Devatoria** [comment]
https://github.com/Devatoria/go-mesos-executor/pull/23
@WinterNis

**Comment by WinterNis** [comment]
Core feature has been merged. Some improvements can be done : 
- Implements an retry count (in the actual implementation, retry will be done indefinitly)
